# Dataset config
TRAIN_PATH = ""
DEV_PATH = ""
TEST_PATH = ""

# Tokenizer config
VOCAB_SIZE = 32000
SPM_MODEL_PATH = ""
PAD_ID = 0
UNK_ID = 1
BOS_ID = 2
EOS_ID = 3

# Training config
BATCH_SIZE = 32
NUM_EPOCHS = 10
LAST_CHECKPOINT_PATH = "last_checkpoint.pt"
BEST_MODEL_PATH = "best_model.pt"
LEARNING_RATE = 3e-4
RESUME_TRAINING = False

# Model Config
TYPE="seq2seq"
MODEL_DIM = 256
STATE_DIM = 16
CONV_KERNEL = 4
HEAD_DIM = 8
MULTILEVEL_CONV_RADIUS = 2
NUM_GROUPS = 1
CHUNK_SIZE = 256
SSM_STATE_DIM = 16
SSM_CONV_KERNEL_SIZE = 4
SSM_NUM_GROUPS = 1
SSM_CHUNK_SIZE = 256
MLCONV_RADIUS = 2
NUM_LAYERS = 4

# Infer config
MAX_NEW_TOKENS = 150
GATE_THRESHOLD = 0.2
PREDS_PATH = "preds.csv"